"""add_yolo_fields_to_colony

Revision ID: c1816f111c3d
Revises: 1b2cc96b8f60
Create Date: 2026-04-26 14:51:55.210177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1816f111c3d'
down_revision: Union[str, None] = '1b2cc96b8f60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('colony', sa.Column('bbox_width', sa.Float(), nullable=True))
    op.add_column('colony', sa.Column('bbox_height', sa.Float(), nullable=True))
    op.add_column('colony', sa.Column('species_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('colony', 'species_name')
    op.drop_column('colony', 'bbox_height')
    op.drop_column('colony', 'bbox_width')
    # ### end Alembic commands ###
